import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';
import RoiCompare from '../../components/RoiCompare';
import { ROI_BAR_DATA } from '../../data/mockData';
import styles from '../admin/RoiPanel.module.css';

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip);

const CHART_OPTIONS = {
  indexAxis: 'y' as const,
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: '#2a2a2a',
      titleColor: '#EFEFEF',
      bodyColor: '#C6C6C6',
      callbacks: { label: (ctx: any) => ` EGP ${ctx.parsed.x}M/yr` },
    },
  },
  scales: {
    x: {
      ticks: { color: '#9B9B9B', font: { family: 'Inter', size: 11 }, callback: (v: number | string) => `${v}M` },
      grid:  { color: 'rgba(255,255,255,0.04)' },
    },
    y: {
      ticks: { color: '#9B9B9B', font: { family: 'Inter', size: 11 } },
      grid:  { color: 'rgba(255,255,255,0.04)' },
    },
  },
};

const chartData = {
  labels: ROI_BAR_DATA.labels,
  datasets: [{
    data: ROI_BAR_DATA.values,
    backgroundColor: [
      'rgba(225,84,29,0.75)',
      'rgba(74,222,128,0.65)',
      'rgba(96,165,250,0.65)',
      'rgba(245,158,11,0.65)',
    ],
    borderRadius: 4,
    barThickness: 22,
  }],
};

export default function RoiPanel() {
  return (
    <div>
      <div className="section-title">Before vs After Makkook.AI</div>
      <RoiCompare />
      <div className="section-title" style={{ marginTop: 24 }}>Value Generated by Category (M EGP/yr)</div>
      <div className={styles.chartWrap}>
        <Bar data={chartData} options={CHART_OPTIONS as any} />
      </div>
    </div>
  );
}
